apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: k8splugin
  name: csi-xfshostpath-plugin
---
kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-xfshostpath-plugin
  namespace: k8splugin
spec:
  selector:
    matchLabels:
      app: csi-xfshostpath-plugin
  template:
    metadata:
      labels:
        app: csi-xfshostpath-plugin
    spec:
      serviceAccountName: csi-xfshostpath-plugin
      nodeSelector:
        "node-role.kubernetes.io/hostpath": "true"
      containers:
        - name: driver-registrar
          image: ihub.helium.io:29006/library/csi-node-driver-registrar:v1.0.2
          resources:
             limits:
               cpu: 0m
               memory: 0Mi
             requests:
               cpu: 0m
               memory: 0Mi
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/data/kubelet/plugins/xfshostpathplugin/csi.sock"
          lifecycle:
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  "rm -rf /registration/csi-cephfsplugin \
                  /registration/csi-xfshostpathplugin-reg.sock"
                ]
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/xfshostpathplugin/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
              readOnly: true
            - name: registration-dir
              mountPath: /registration
        - name: plugin 
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true 
          image: ihub.helium.io:29006/library/hostpathcsi:v1.0.0
          imagePullPolicy: "Always"
          resources:
             limits:
               cpu: 0m
               memory: 0Mi
             requests:
               cpu: 0m
               memory: 0Mi
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--drivername=xfshostpathplugin"
            - "--nodename=$(KUBE_NODE_NAME)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://var/lib/kubelet/plugins/xfshostpathplugin/csi.sock           
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/xfshostpathplugin
            - name: csi-plugins-dir
              mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
              mountPropagation: "Bidirectional"
            - name: pods-mount-dir
              mountPath: /data/kubelet/pods
              mountPropagation: "Bidirectional"
            - mountPath: /dev
              name: host-dev
            - mountPath: /etc/projects
              name: host-etc-projects
            - mountPath: /etc/projid
              name: host-etc-projid
            - mountPath: /sys
              name: host-sys
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /xfs
              name: quotadir
      volumes:
        - name: plugin-dir
          hostPath:
            path: /data/kubelet/plugins/xfshostpathplugin
            type: DirectoryOrCreate
        - name: csi-plugins-dir
          hostPath:
            path: /data/kubelet/plugins/kubernetes.io/csi
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /data/kubelet/pods
            type: Directory
        - name: socket-dir
          hostPath:
            path: /data/kubelet/plugins/xfshostpathplugin
            type: DirectoryOrCreate
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-etc-projects
          hostPath:
            path: /etc/projects
            type: FileOrCreate
        - name: host-etc-projid
          hostPath:
            path: /etc/projid
            type: FileOrCreate
        - name: host-sys
          hostPath:
            path: /sys
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: quotadir
          hostPath:
            path: /xfs
        - name: registration-dir
          hostPath:
            path: /data/kubelet/plugins_registry/
            type: Directory
